todoAspnetmvcUi/Components/NavigationMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations;
using todoAspnetmvcUi.Models.Repository;

namespace todoAspnetmvcUi.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IListRepository repository;

        public NavigationMenuViewComponent(IListRepository repository)
        {
            this.repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Todo_Lists
               .Select(x => x.Category)
               .Distinct());
        }
    }

}

todoAspnetmvcUi/Views/Shared/_EditLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet" />
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Organizer Application</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-light bg-light p-2">
        <span class="navbar-brand mb-0 h1 ml-2">Organizer</span>
    </nav>
    <div class="container-fluid">
        <div class="row p-2">
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

todoAspnetmvcUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet" />
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Organizer Application</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-light bg-light p-2">
        <span class="navbar-brand mb-0 h1 ml-2">Organizer</span>
    </nav>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:navigation-menu />
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>

todoAspnetmvcUi/Views/Shared/_ListSummary.cshtml
@model todo_domain_entities.Todo_List

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model?.Name
            <span class="badge rounded-pill bg-primary text-white"
                  style="float:right">
                <a class="btn btn-dark btn-sm" asp-action="Details" asp-route-productId="@Model.Id">
                    <i class="fa fa-external-link-square"></i>
                </a>
                <a class="btn btn-secondary btn-sm" asp-action="Edit" asp-route-productId="@Model.Id">
                    <i class="fa fa-pencil-square"></i>
                </a>
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-productId="@Model.Id">
                    <i class="fa fa-minus-square"></i>
                </a>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">@Model?.Description</div>
    <table class="table table-sm table-bordered table-striped">
        <tbody>
            @foreach (var p in Model.Tasks)
            {
                <tr>
                    <td>@p.Name</td>
                    <td>@p.Tasks</td>
                    <td>@p.DateStart</td>
                    <td>@p.Date</td>
                    @if (p.IsComplete == false)
                    {
                        <td>
                            <a class="btn btn btn-warning btn-sm" asp-action="Complete" asp-route-productId="@p.Id">
                                Uncomplete
                            </a>
                        </td>
                    }
                    else
                    {
                        <td>
                            <a class="btn btn btn-success btn-sm" asp-action="Complete" asp-route-productId="@p.Id">
                                Complete
                            </a>
                        </td>
                    }
                </tr>
            }
            <tr>
                <td>
                    <a class="btn btn btn-primary btn-sm" asp-action="AddTask" asp-route-productId="@Model.Id">
                        Add Task
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

todoAspnetmvcUi/Views/Shared/_ListSummaryToday.cshtml
@model todo_domain_entities.Todo_List

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model?.Name
            <span class="badge rounded-pill bg-primary text-white"
                  style="float:right">
                <a class="btn btn-dark btn-sm" asp-action="Details" asp-route-productId="@Model.Id">
                    <i class="fa fa-external-link-square"></i>
                </a>
                <a class="btn btn-secondary btn-sm" asp-action="Edit" asp-route-productId="@Model.Id">
                    <i class="fa fa-pencil-square"></i>
                </a>
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-productId="@Model.Id">
                    <i class="fa fa-minus-square"></i>
                </a>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">@Model?.Description</div>
    <table class="table table-sm table-bordered table-striped">
        <tbody>
            @foreach (var p in Model.Tasks)
            {
                if (p.Date.Date == DateTime.Today)
                {
                    <tr>
                        <td>@p.Name</td>
                        <td>@p.Tasks</td>
                        <td>@p.DateStart</td>
                        <td>@p.Date</td>
                        @if (p.IsComplete == false)
                        {
                            <td>
                                <a class="btn btn btn-warning btn-sm" asp-action="Complete" asp-route-productId="@p.Id">
                                    Uncomplete
                                </a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a class="btn btn btn-success btn-sm" asp-action="Complete" asp-route-productId="@p.Id">
                                    Complete
                                </a>
                            </td>
                        }
                    </tr>
                }
                }
            <tr>
                <td>
                    <a class="btn btn btn-primary btn-sm" asp-action="AddTask" asp-route-productId="@Model.Id">
                        Add Task
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>